<?php

$term = $_GET["term"];
$stations = array(
    array("label" => "'s-Hertogenbosch", "value" => "'s-Hertogenbosch"),
    array("label" => "'s-Hertogenbosch Oost", "value" => "'s-Hertogenbosch Oost"),
    array("label" => "'t Harde", "value" => "'t Harde"),
    array("label" => "Aachen Hbf", "value" => "Aachen Hbf"),
    array("label" => "Aalten", "value" => "Aalten"),
    array("label" => "Abcoude", "value" => "Abcoude"),
    array("label" => "Ahaus", "value" => "Ahaus"),
    array("label" => "Aime-la-Plagne", "value" => "Aime-la-Plagne"),
    array("label" => "Aix-en-Provence", "value" => "Aix-en-Provence"),
    array("label" => "Akkrum", "value" => "Akkrum"),
    array("label" => "Albertville", "value" => "Albertville"),
    array("label" => "Alessandria", "value" => "Alessandria"),
    array("label" => "Alkmaar", "value" => "Alkmaar"),
    array("label" => "Alkmaar Noord", "value" => "Alkmaar Noord"),
    array("label" => "Almelo", "value" => "Almelo"),
    array("label" => "Almelo de Riet", "value" => "Almelo de Riet"),
    array("label" => "Almere Buiten", "value" => "Almere Buiten"),
    array("label" => "Almere Centrum", "value" => "Almere Centrum"),
    array("label" => "Almere Muziekwijk", "value" => "Almere Muziekwijk"),
    array("label" => "Almere Oostvaarders", "value" => "Almere Oostvaarders"),
    array("label" => "Almere Parkwijk", "value" => "Almere Parkwijk"),
    array("label" => "Almere Poort", "value" => "Almere Poort"),
    array("label" => "Alphen a/d Rijn", "value" => "Alphen a/d Rijn"),
    array("label" => "Altenberge", "value" => "Altenberge"),
    array("label" => "Amersfoort", "value" => "Amersfoort"),
    array("label" => "Amersfoort Schothorst", "value" => "Amersfoort Schothorst"),
    array("label" => "Amersfoort Vathorst", "value" => "Amersfoort Vathorst"),
    array("label" => "Amsterdam Amstel", "value" => "Amsterdam Amstel"),
    array("label" => "Amsterdam Bijlmer ArenA", "value" => "Amsterdam Bijlmer ArenA"),
    array("label" => "Amsterdam Centraal", "value" => "Amsterdam Centraal"),
    array("label" => "Amsterdam Holendrecht", "value" => "Amsterdam Holendrecht"),
    array("label" => "Amsterdam Lelylaan", "value" => "Amsterdam Lelylaan"),
    array("label" => "Amsterdam Muiderpoort", "value" => "Amsterdam Muiderpoort"),
    array("label" => "Amsterdam RAI", "value" => "Amsterdam RAI"),
    array("label" => "Amsterdam Science Park", "value" => "Amsterdam Science Park"),
    array("label" => "Amsterdam Sloterdijk", "value" => "Amsterdam Sloterdijk"),
    array("label" => "Amsterdam Van der Madeweg", "value" => "Amsterdam Van der Madeweg"),
    array("label" => "Amsterdam Zuid", "value" => "Amsterdam Zuid"),
    array("label" => "Anna Paulowna", "value" => "Anna Paulowna"),
    array("label" => "Antwerpen-Berchem", "value" => "Antwerpen-Berchem"),
    array("label" => "Antwerpen-Centraal", "value" => "Antwerpen-Centraal"),
    array("label" => "Antwerpen-Luchtbal", "value" => "Antwerpen-Luchtbal"),
    array("label" => "Antwerpen-Noorderdokken", "value" => "Antwerpen-Noorderdokken"),
    array("label" => "Antwerpen-Zuid", "value" => "Antwerpen-Zuid"),
    array("label" => "Apeldoorn", "value" => "Apeldoorn"),
    array("label" => "Apeldoorn De Maten", "value" => "Apeldoorn De Maten"),
    array("label" => "Apeldoorn Osseveld", "value" => "Apeldoorn Osseveld"),
    array("label" => "Appingedam", "value" => "Appingedam"),
    array("label" => "Arkel", "value" => "Arkel"),
    array("label" => "Arnemuiden", "value" => "Arnemuiden"),
    array("label" => "Arnhem Centraal", "value" => "Arnhem Centraal"),
    array("label" => "Arnhem Presikhaaf", "value" => "Arnhem Presikhaaf"),
    array("label" => "Arnhem Velperpoort", "value" => "Arnhem Velperpoort"),
    array("label" => "Arnhem Zuid", "value" => "Arnhem Zuid"),
    array("label" => "Ashford International", "value" => "Ashford International"),
    array("label" => "Assen", "value" => "Assen"),
    array("label" => "Augsburg Hbf", "value" => "Augsburg Hbf"),
    array("label" => "Avignon TGV", "value" => "Avignon TGV"),
    array("label" => "Baarn", "value" => "Baarn"),
    array("label" => "Bad Bentheim", "value" => "Bad Bentheim"),
    array("label" => "Bad Nieuweschans", "value" => "Bad Nieuweschans"),
    array("label" => "Bad Oeynhausen", "value" => "Bad Oeynhausen"),
    array("label" => "Bad Schandau", "value" => "Bad Schandau"),
    array("label" => "Baden", "value" => "Baden"),
    array("label" => "Baden-Baden", "value" => "Baden-Baden"),
    array("label" => "Baflo", "value" => "Baflo"),
    array("label" => "Barendrecht", "value" => "Barendrecht"),
    array("label" => "Barneveld Centrum", "value" => "Barneveld Centrum"),
    array("label" => "Barneveld Noord", "value" => "Barneveld Noord"),
    array("label" => "Barneveld Zuid", "value" => "Barneveld Zuid"),
    array("label" => "Basel Bad Bf", "value" => "Basel Bad Bf"),
    array("label" => "Basel SBB", "value" => "Basel SBB"),
    array("label" => "Bedum", "value" => "Bedum"),
    array("label" => "Beek-Elsloo", "value" => "Beek-Elsloo"),
    array("label" => "Beesd", "value" => "Beesd"),
    array("label" => "Beilen", "value" => "Beilen"),
    array("label" => "Belsele", "value" => "Belsele"),
    array("label" => "Bergen op Zoom", "value" => "Bergen op Zoom"),
    array("label" => "Berlin Hbf", "value" => "Berlin Hbf"),
    array("label" => "Berlin Hbf (tief)", "value" => "Berlin Hbf (tief)"),
    array("label" => "Berlin Ostbahnhof", "value" => "Berlin Ostbahnhof"),
    array("label" => "Berlin SÃ¼dkreuz", "value" => "Berlin SÃ¼dkreuz"),
    array("label" => "Berlin-SchÃ¶nefeld Flug.", "value" => "Berlin-SchÃ¶nefeld Flug."),
    array("label" => "Berlin-Spandau", "value" => "Berlin-Spandau"),
    array("label" => "Best", "value" => "Best"),
    array("label" => "Beveren", "value" => "Beveren"),
    array("label" => "Beverwijk", "value" => "Beverwijk"),
    array("label" => "Bielefeld Hbf", "value" => "Bielefeld Hbf"),
    array("label" => "Bilthoven", "value" => "Bilthoven"),
    array("label" => "Bilzen", "value" => "Bilzen"),
    array("label" => "Bischofshofen", "value" => "Bischofshofen"),
    array("label" => "Blerick", "value" => "Blerick"),
    array("label" => "Bloemendaal", "value" => "Bloemendaal"),
    array("label" => "Bludenz", "value" => "Bludenz"),
    array("label" => "Bodegraven", "value" => "Bodegraven"),
    array("label" => "Boisheim", "value" => "Boisheim"),
    array("label" => "Bonn Hbf", "value" => "Bonn Hbf"),
    array("label" => "Boom", "value" => "Boom"),
    array("label" => "Bork", "value" => "Bork"),
    array("label" => "Borne", "value" => "Borne"),
    array("label" => "Boskoop", "value" => "Boskoop"),
    array("label" => "Bourg-St-Maurice", "value" => "Bourg-St-Maurice"),
    array("label" => "Boven-Hardinxveld", "value" => "Boven-Hardinxveld"),
    array("label" => "Bovenkarspel Flora", "value" => "Bovenkarspel Flora"),
    array("label" => "Bovenkarspel-Grootebroek", "value" => "Bovenkarspel-Grootebroek"),
    array("label" => "Boxmeer", "value" => "Boxmeer"),
    array("label" => "Boxtel", "value" => "Boxtel"),
    array("label" => "Braunschweig Hbf", "value" => "Braunschweig Hbf"),
    array("label" => "Breda", "value" => "Breda"),
    array("label" => "Breda-Prinsenbeek", "value" => "Breda-Prinsenbeek"),
    array("label" => "Bressoux", "value" => "Bressoux"),
    array("label" => "Breukelen", "value" => "Breukelen"),
    array("label" => "Breyell", "value" => "Breyell"),
    array("label" => "Brummen", "value" => "Brummen"),
    array("label" => "Brussel-Centraal", "value" => "Brussel-Centraal"),
    array("label" => "Brussel-Noord", "value" => "Brussel-Noord"),
    array("label" => "Brussel-Zuid/Midi", "value" => "Brussel-Zuid/Midi"),
    array("label" => "Brussels Airport-Zaventem", "value" => "Brussels Airport-Zaventem"),
    array("label" => "Budapest", "value" => "Budapest"),
    array("label" => "Buitenpost", "value" => "Buitenpost"),
    array("label" => "Bunde", "value" => "Bunde"),
    array("label" => "Bunnik", "value" => "Bunnik"),
    array("label" => "Bussum Zuid", "value" => "Bussum Zuid"),
    array("label" => "BÃ¶nen", "value" => "BÃ¶nen"),
    array("label" => "BÃ¼nde (Westf)", "value" => "BÃ¼nde (Westf)"),
    array("label" => "Capelle Schollevaar", "value" => "Capelle Schollevaar"),
    array("label" => "Castricum", "value" => "Castricum"),
    array("label" => "ChambÃ©ry", "value" => "ChambÃ©ry"),
    array("label" => "Chevremont", "value" => "Chevremont"),
    array("label" => "Chur", "value" => "Chur"),
    array("label" => "Coesfeld (Westf)", "value" => "Coesfeld (Westf)"),
    array("label" => "Coevorden", "value" => "Coevorden"),
    array("label" => "Como", "value" => "Como"),
    array("label" => "Cuijk", "value" => "Cuijk"),
    array("label" => "Culemborg", "value" => "Culemborg"),
    array("label" => "Daarlerveen", "value" => "Daarlerveen"),
    array("label" => "Dalen", "value" => "Dalen"),
    array("label" => "Dalfsen", "value" => "Dalfsen"),
    array("label" => "De Vink", "value" => "De Vink"),
    array("label" => "De Westereen", "value" => "De Westereen"),
    array("label" => "Decin hl.n.", "value" => "Decin hl.n."),
    array("label" => "Deinum", "value" => "Deinum"),
    array("label" => "Delden", "value" => "Delden"),
    array("label" => "Delft", "value" => "Delft"),
    array("label" => "Delft Zuid", "value" => "Delft Zuid"),
    array("label" => "Delfzijl", "value" => "Delfzijl"),
    array("label" => "Delfzijl West", "value" => "Delfzijl West"),
    array("label" => "Den Dolder", "value" => "Den Dolder"),
    array("label" => "Den Haag Centraal", "value" => "Den Haag Centraal"),
    array("label" => "Den Haag HS", "value" => "Den Haag HS"),
    array("label" => "Den Haag Laan v NOI", "value" => "Den Haag Laan v NOI"),
    array("label" => "Den Haag Mariahoeve", "value" => "Den Haag Mariahoeve"),
    array("label" => "Den Haag Moerwijk", "value" => "Den Haag Moerwijk"),
    array("label" => "Den Haag Ypenburg", "value" => "Den Haag Ypenburg"),
    array("label" => "Den Helder", "value" => "Den Helder"),
    array("label" => "Den Helder Zuid", "value" => "Den Helder Zuid"),
    array("label" => "Deurne", "value" => "Deurne"),
    array("label" => "Deventer", "value" => "Deventer"),
    array("label" => "Deventer Colmschate", "value" => "Deventer Colmschate"),
    array("label" => "Didam", "value" => "Didam"),
    array("label" => "Diemen", "value" => "Diemen"),
    array("label" => "Diemen Zuid", "value" => "Diemen Zuid"),
    array("label" => "Diepenbeek", "value" => "Diepenbeek"),
    array("label" => "Dieren", "value" => "Dieren"),
    array("label" => "Doetinchem", "value" => "Doetinchem"),
    array("label" => "Doetinchem De Huet", "value" => "Doetinchem De Huet"),
    array("label" => "Domodossola", "value" => "Domodossola"),
    array("label" => "Dordrecht", "value" => "Dordrecht"),
    array("label" => "Dordrecht Stadspolders", "value" => "Dordrecht Stadspolders"),
    array("label" => "Dordrecht Zuid", "value" => "Dordrecht Zuid"),
    array("label" => "Dortmund Derne", "value" => "Dortmund Derne"),
    array("label" => "Dortmund Hbf", "value" => "Dortmund Hbf"),
    array("label" => "Dortmund Kirchderne", "value" => "Dortmund Kirchderne"),
    array("label" => "Dresden Hbf", "value" => "Dresden Hbf"),
    array("label" => "Dresden-Neustadt", "value" => "Dresden-Neustadt"),
    array("label" => "Driebergen-Zeist", "value" => "Driebergen-Zeist"),
    array("label" => "Driehuis", "value" => "Driehuis"),
    array("label" => "Dronryp", "value" => "Dronryp"),
    array("label" => "Dronten", "value" => "Dronten"),
    array("label" => "Duffel", "value" => "Duffel"),
    array("label" => "Duisburg Hbf", "value" => "Duisburg Hbf"),
    array("label" => "Duiven", "value" => "Duiven"),
    array("label" => "Duivendrecht", "value" => "Duivendrecht"),
    array("label" => "DÃ¼lken", "value" => "DÃ¼lken"),
    array("label" => "DÃ¼lmen", "value" => "DÃ¼lmen"),
    array("label" => "DÃ¼sseldorf Hbf", "value" => "DÃ¼sseldorf Hbf"),
    array("label" => "Ebbsfleet International", "value" => "Ebbsfleet International"),
    array("label" => "Echt", "value" => "Echt"),
    array("label" => "Ede Centrum", "value" => "Ede Centrum"),
    array("label" => "Ede-Wageningen", "value" => "Ede-Wageningen"),
    array("label" => "Eijs-Wittem", "value" => "Eijs-Wittem"),
    array("label" => "Eijsden", "value" => "Eijsden"),
    array("label" => "Eindhoven", "value" => "Eindhoven"),
    array("label" => "Eindhoven Strijp-S", "value" => "Eindhoven Strijp-S"),
    array("label" => "Ekeren", "value" => "Ekeren"),
    array("label" => "Elst", "value" => "Elst"),
    array("label" => "Emmen", "value" => "Emmen"),
    array("label" => "Emmen Zuid", "value" => "Emmen Zuid"),
    array("label" => "Emmerich", "value" => "Emmerich"),
    array("label" => "Enkhuizen", "value" => "Enkhuizen"),
    array("label" => "Ennepetal (Gevelsberg)", "value" => "Ennepetal (Gevelsberg)"),
    array("label" => "Enschede", "value" => "Enschede"),
    array("label" => "Enschede De Eschmarke", "value" => "Enschede De Eschmarke"),
    array("label" => "Enschede Kennispark", "value" => "Enschede Kennispark"),
    array("label" => "Epe (Westf)", "value" => "Epe (Westf)"),
    array("label" => "Ermelo", "value" => "Ermelo"),
    array("label" => "Essen (Belgie)", "value" => "Essen (Belgie)"),
    array("label" => "Etten-Leur", "value" => "Etten-Leur"),
    array("label" => "Eygelshoven", "value" => "Eygelshoven"),
    array("label" => "Eygelshoven Markt", "value" => "Eygelshoven Markt"),
    array("label" => "Feanwalden", "value" => "Feanwalden"),
    array("label" => "Fieberbrunn", "value" => "Fieberbrunn"),
    array("label" => "Franeker", "value" => "Franeker"),
    array("label" => "Frankfurt (M) Hbf", "value" => "Frankfurt (M) Hbf"),
    array("label" => "Frankfurt (Oder)", "value" => "Frankfurt (Oder)"),
    array("label" => "Frankfurt Flughafen Fernb", "value" => "Frankfurt Flughafen Fernb"),
    array("label" => "Freiburg (Breisgau) Hbf", "value" => "Freiburg (Breisgau) Hbf"),
    array("label" => "Gaanderen", "value" => "Gaanderen"),
    array("label" => "Geislingen", "value" => "Geislingen"),
    array("label" => "Geldermalsen", "value" => "Geldermalsen"),
    array("label" => "Geldrop", "value" => "Geldrop"),
    array("label" => "Geleen Oost", "value" => "Geleen Oost"),
    array("label" => "Geleen-Lutterade", "value" => "Geleen-Lutterade"),
    array("label" => "Gilze-Rijen", "value" => "Gilze-Rijen"),
    array("label" => "Glanerbrug", "value" => "Glanerbrug"),
    array("label" => "Glons", "value" => "Glons"),
    array("label" => "Goes", "value" => "Goes"),
    array("label" => "Goor", "value" => "Goor"),
    array("label" => "Gorinchem", "value" => "Gorinchem"),
    array("label" => "Gouda", "value" => "Gouda"),
    array("label" => "Gouda Goverwelle", "value" => "Gouda Goverwelle"),
    array("label" => "Gramsbergen", "value" => "Gramsbergen"),
    array("label" => "Grijpskerk", "value" => "Grijpskerk"),
    array("label" => "Gronau (Westf.)", "value" => "Gronau (Westf.)"),
    array("label" => "Groningen", "value" => "Groningen"),
    array("label" => "Groningen Europapark", "value" => "Groningen Europapark"),
    array("label" => "Groningen Noord", "value" => "Groningen Noord"),
    array("label" => "Grou-Jirnsum", "value" => "Grou-Jirnsum"),
    array("label" => "Gulpen-Wijlre", "value" => "Gulpen-Wijlre"),
    array("label" => "GÃ¶ppingen", "value" => "GÃ¶ppingen"),
    array("label" => "GÃ¼nzburg", "value" => "GÃ¼nzburg"),
    array("label" => "Haarlem", "value" => "Haarlem"),
    array("label" => "Haarlem Spaarnwoude", "value" => "Haarlem Spaarnwoude"),
    array("label" => "Hagen Hbf", "value" => "Hagen Hbf"),
    array("label" => "Halfweg-Zwanenburg", "value" => "Halfweg-Zwanenburg"),
    array("label" => "Hamburg Hbf", "value" => "Hamburg Hbf"),
    array("label" => "Hamm (Westf.)", "value" => "Hamm (Westf.)"),
    array("label" => "Hannover Hbf", "value" => "Hannover Hbf"),
    array("label" => "Hardenberg", "value" => "Hardenberg"),
    array("label" => "Harderwijk", "value" => "Harderwijk"),
    array("label" => "Hardinxveld Blauwe Zoom", "value" => "Hardinxveld Blauwe Zoom"),
    array("label" => "Hardinxveld-Giessendam", "value" => "Hardinxveld-Giessendam"),
    array("label" => "Haren", "value" => "Haren"),
    array("label" => "Harlingen", "value" => "Harlingen"),
    array("label" => "Harlingen Haven", "value" => "Harlingen Haven"),
    array("label" => "Hasselt", "value" => "Hasselt"),
    array("label" => "Heemskerk", "value" => "Heemskerk"),
    array("label" => "Heemstede-Aerdenhout", "value" => "Heemstede-Aerdenhout"),
    array("label" => "Heerenveen", "value" => "Heerenveen"),
    array("label" => "Heerenveen IJsstadion", "value" => "Heerenveen IJsstadion"),
    array("label" => "Heerhugowaard", "value" => "Heerhugowaard"),
    array("label" => "Heerlen", "value" => "Heerlen"),
    array("label" => "Heerlen De Kissel", "value" => "Heerlen De Kissel"),
    array("label" => "Heerlen Woonboulevard", "value" => "Heerlen Woonboulevard"),
    array("label" => "Heeze", "value" => "Heeze"),
    array("label" => "Heide", "value" => "Heide"),
    array("label" => "Heiloo", "value" => "Heiloo"),
    array("label" => "Heino", "value" => "Heino"),
    array("label" => "Helmond", "value" => "Helmond"),
    array("label" => "Helmond 't Hout", "value" => "Helmond 't Hout"),
    array("label" => "Helmond Brandevoort", "value" => "Helmond Brandevoort"),
    array("label" => "Helmond Brouwhuis", "value" => "Helmond Brouwhuis"),
    array("label" => "Hemiksem", "value" => "Hemiksem"),
    array("label" => "Hemmen-Dodewaard", "value" => "Hemmen-Dodewaard"),
    array("label" => "Hengelo", "value" => "Hengelo"),
    array("label" => "Hengelo Gezondheidspark", "value" => "Hengelo Gezondheidspark"),
    array("label" => "Hengelo Oost", "value" => "Hengelo Oost"),
    array("label" => "Herstal", "value" => "Herstal"),
    array("label" => "Herzogenrath", "value" => "Herzogenrath"),
    array("label" => "Hillegom", "value" => "Hillegom"),
    array("label" => "Hilversum", "value" => "Hilversum"),
    array("label" => "Hilversum Media Park", "value" => "Hilversum Media Park"),
    array("label" => "Hilversum Sportpark", "value" => "Hilversum Sportpark"),
    array("label" => "Hindeloopen", "value" => "Hindeloopen"),
    array("label" => "Hoboken-Polder", "value" => "Hoboken-Polder"),
    array("label" => "Hoek van Holland Haven", "value" => "Hoek van Holland Haven"),
    array("label" => "Hoek van Holland Strand", "value" => "Hoek van Holland Strand"),
    array("label" => "Hoensbroek", "value" => "Hoensbroek"),
    array("label" => "Hoevelaken", "value" => "Hoevelaken"),
    array("label" => "Hollandsche Rading", "value" => "Hollandsche Rading"),
    array("label" => "Holten", "value" => "Holten"),
    array("label" => "Holzwickede", "value" => "Holzwickede"),
    array("label" => "Hoofddorp", "value" => "Hoofddorp"),
    array("label" => "Hoogeveen", "value" => "Hoogeveen"),
    array("label" => "Hoogezand-Sappemeer", "value" => "Hoogezand-Sappemeer"),
    array("label" => "Hoogkarspel", "value" => "Hoogkarspel"),
    array("label" => "Hoorn", "value" => "Hoorn"),
    array("label" => "Hoorn Kersenboogerd", "value" => "Hoorn Kersenboogerd"),
    array("label" => "Hopfgarten", "value" => "Hopfgarten"),
    array("label" => "Horst-Sevenum", "value" => "Horst-Sevenum"),
    array("label" => "Houten", "value" => "Houten"),
    array("label" => "Houten Castellum", "value" => "Houten Castellum"),
    array("label" => "Houthem-St Gerlach", "value" => "Houthem-St Gerlach"),
    array("label" => "Hove", "value" => "Hove"),
    array("label" => "Hurdegaryp", "value" => "Hurdegaryp"),
    array("label" => "IJlst", "value" => "IJlst"),
    array("label" => "Innsbruck Hbf", "value" => "Innsbruck Hbf"),
    array("label" => "Jenbach", "value" => "Jenbach"),
    array("label" => "Kaldenkirchen", "value" => "Kaldenkirchen"),
    array("label" => "Kalmthout", "value" => "Kalmthout"),
    array("label" => "Kampen", "value" => "Kampen"),
    array("label" => "Kampen Zuid", "value" => "Kampen Zuid"),
    array("label" => "Kapelle-Biezelinge", "value" => "Kapelle-Biezelinge"),
    array("label" => "Kapellen", "value" => "Kapellen"),
    array("label" => "Karlsruhe Hbf", "value" => "Karlsruhe Hbf"),
    array("label" => "Kerkrade Centrum", "value" => "Kerkrade Centrum"),
    array("label" => "Kerkrade West", "value" => "Kerkrade West"),
    array("label" => "Kesteren", "value" => "Kesteren"),
    array("label" => "Kijkuit", "value" => "Kijkuit"),
    array("label" => "Kirchberg in Tirol", "value" => "Kirchberg in Tirol"),
    array("label" => "KitzbÃ¼hel", "value" => "KitzbÃ¼hel"),
    array("label" => "Klarenbeek", "value" => "Klarenbeek"),
    array("label" => "Klimmen-Ransdaal", "value" => "Klimmen-Ransdaal"),
    array("label" => "Koblenz Hbf", "value" => "Koblenz Hbf"),
    array("label" => "Konin", "value" => "Konin"),
    array("label" => "Kontich", "value" => "Kontich"),
    array("label" => "Koog Bloemwijk", "value" => "Koog Bloemwijk"),
    array("label" => "Koog-Zaandijk", "value" => "Koog-Zaandijk"),
    array("label" => "Koudum-Molkwerum", "value" => "Koudum-Molkwerum"),
    array("label" => "Krabbendijke", "value" => "Krabbendijke"),
    array("label" => "Krommenie-Assendelft", "value" => "Krommenie-Assendelft"),
    array("label" => "Kropswolde", "value" => "Kropswolde"),
    array("label" => "Kruiningen-Yerseke", "value" => "Kruiningen-Yerseke"),
    array("label" => "Kufstein", "value" => "Kufstein"),
    array("label" => "Kutno", "value" => "Kutno"),
    array("label" => "KÃ¶ln Hbf", "value" => "KÃ¶ln Hbf"),
    array("label" => "KÃ¶ln-Deutz", "value" => "KÃ¶ln-Deutz"),
    array("label" => "Lage Zwaluwe", "value" => "Lage Zwaluwe"),
    array("label" => "Landeck", "value" => "Landeck"),
    array("label" => "Landgraaf", "value" => "Landgraaf"),
    array("label" => "Landquart", "value" => "Landquart"),
    array("label" => "Landry", "value" => "Landry"),
    array("label" => "Leer (Ostfriesland)", "value" => "Leer (Ostfriesland)"),
    array("label" => "Leerdam", "value" => "Leerdam"),
    array("label" => "Leeuwarden", "value" => "Leeuwarden"),
    array("label" => "Leeuwarden Achter d Hoven", "value" => "Leeuwarden Achter d Hoven"),
    array("label" => "Leeuwarden Camminghaburen", "value" => "Leeuwarden Camminghaburen"),
    array("label" => "Legden", "value" => "Legden"),
    array("label" => "Leiden Centraal", "value" => "Leiden Centraal"),
    array("label" => "Leiden Lammenschans", "value" => "Leiden Lammenschans"),
    array("label" => "Lelystad Centrum", "value" => "Lelystad Centrum"),
    array("label" => "Lette (Kr Coersfeld)", "value" => "Lette (Kr Coersfeld)"),
    array("label" => "Leuven", "value" => "Leuven"),
    array("label" => "Lichtenvoorde-Groenlo", "value" => "Lichtenvoorde-Groenlo"),
    array("label" => "Liers", "value" => "Liers"),
    array("label" => "Lille Europe", "value" => "Lille Europe"),
    array("label" => "Limburg SÃ¼d", "value" => "Limburg SÃ¼d"),
    array("label" => "Livorno Centrale", "value" => "Livorno Centrale"),
    array("label" => "LiÃ¨ge-Guillemins", "value" => "LiÃ¨ge-Guillemins"),
    array("label" => "LiÃ¨ge-Jonfosse", "value" => "LiÃ¨ge-Jonfosse"),
    array("label" => "LiÃ¨ge-Palais", "value" => "LiÃ¨ge-Palais"),
    array("label" => "Lochem", "value" => "Lochem"),
    array("label" => "Lokeren", "value" => "Lokeren"),
    array("label" => "London St. Pancras", "value" => "London St. Pancras"),
    array("label" => "Loppersum", "value" => "Loppersum"),
    array("label" => "Lourdes", "value" => "Lourdes"),
    array("label" => "Lunteren", "value" => "Lunteren"),
    array("label" => "LÃ¼dinghausen", "value" => "LÃ¼dinghausen"),
    array("label" => "LÃ¼nen Hbf", "value" => "LÃ¼nen Hbf"),
    array("label" => "Maarheeze", "value" => "Maarheeze"),
    array("label" => "Maarn", "value" => "Maarn"),
    array("label" => "Maarssen", "value" => "Maarssen"),
    array("label" => "Maassluis", "value" => "Maassluis"),
    array("label" => "Maassluis West", "value" => "Maassluis West"),
    array("label" => "Maastricht", "value" => "Maastricht"),
    array("label" => "Maastricht Noord", "value" => "Maastricht Noord"),
    array("label" => "Maastricht Randwyck", "value" => "Maastricht Randwyck"),
    array("label" => "Mainz Hbf", "value" => "Mainz Hbf"),
    array("label" => "Mannheim Hbf", "value" => "Mannheim Hbf"),
    array("label" => "Mantgum", "value" => "Mantgum"),
    array("label" => "MariÃ«nberg", "value" => "MariÃ«nberg"),
    array("label" => "Marne-la-VallÃ©e-Chessy", "value" => "Marne-la-VallÃ©e-Chessy"),
    array("label" => "Marseille-St-Charles", "value" => "Marseille-St-Charles"),
    array("label" => "Martenshoek", "value" => "Martenshoek"),
    array("label" => "Mechelen", "value" => "Mechelen"),
    array("label" => "Mechelen-Nekkerspoel", "value" => "Mechelen-Nekkerspoel"),
    array("label" => "Meerssen", "value" => "Meerssen"),
    array("label" => "Melsele", "value" => "Melsele"),
    array("label" => "Meppel", "value" => "Meppel"),
    array("label" => "Metelen Land", "value" => "Metelen Land"),
    array("label" => "Middelburg", "value" => "Middelburg"),
    array("label" => "Milmort", "value" => "Milmort"),
    array("label" => "Minden (Westf.)", "value" => "Minden (Westf.)"),
    array("label" => "Montabaur", "value" => "Montabaur"),
    array("label" => "Mook Molenhoek", "value" => "Mook Molenhoek"),
    array("label" => "Mortsel-Deurnesteenweg", "value" => "Mortsel-Deurnesteenweg"),
    array("label" => "Mortsel-Oude God", "value" => "Mortsel-Oude God"),
    array("label" => "Moutiers-Salins-Brides", "value" => "Moutiers-Salins-Brides"),
    array("label" => "MÃ¶nchengladbach Hbf", "value" => "MÃ¶nchengladbach Hbf"),
    array("label" => "MÃ¼nchen Hbf", "value" => "MÃ¼nchen Hbf"),
    array("label" => "MÃ¼nster (Westf.) Hbf", "value" => "MÃ¼nster (Westf.) Hbf"),
    array("label" => "MÃ¼nster Zentrum Nord", "value" => "MÃ¼nster Zentrum Nord"),
    array("label" => "MÃ¼nster-HÃ¤ger", "value" => "MÃ¼nster-HÃ¤ger"),
    array("label" => "Naarden-Bussum", "value" => "Naarden-Bussum"),
    array("label" => "Neuss Hbf", "value" => "Neuss Hbf"),
    array("label" => "Niel", "value" => "Niel"),
    array("label" => "Nieuw Amsterdam", "value" => "Nieuw Amsterdam"),
    array("label" => "Nieuw Vennep", "value" => "Nieuw Vennep"),
    array("label" => "Nieuwerkerk a/d IJssel", "value" => "Nieuwerkerk a/d IJssel"),
    array("label" => "Nieuwkerken-Waas", "value" => "Nieuwkerken-Waas"),
    array("label" => "Nijkerk", "value" => "Nijkerk"),
    array("label" => "Nijmegen", "value" => "Nijmegen"),
    array("label" => "Nijmegen Dukenburg", "value" => "Nijmegen Dukenburg"),
    array("label" => "Nijmegen Goffert", "value" => "Nijmegen Goffert"),
    array("label" => "Nijmegen Heyendaal", "value" => "Nijmegen Heyendaal"),
    array("label" => "Nijmegen Lent", "value" => "Nijmegen Lent"),
    array("label" => "Nijverdal", "value" => "Nijverdal"),
    array("label" => "Noorderkempen", "value" => "Noorderkempen"),
    array("label" => "Nordwalde", "value" => "Nordwalde"),
    array("label" => "Nunspeet", "value" => "Nunspeet"),
    array("label" => "Nuth", "value" => "Nuth"),
    array("label" => "NÃ¼rnberg Hbf", "value" => "NÃ¼rnberg Hbf"),
    array("label" => "Obdam", "value" => "Obdam"),
    array("label" => "Oberhausen Hbf", "value" => "Oberhausen Hbf"),
    array("label" => "Ochtrup", "value" => "Ochtrup"),
    array("label" => "Offenburg", "value" => "Offenburg"),
    array("label" => "Oisterwijk", "value" => "Oisterwijk"),
    array("label" => "Oldenzaal", "value" => "Oldenzaal"),
    array("label" => "Olst", "value" => "Olst"),
    array("label" => "Ommen", "value" => "Ommen"),
    array("label" => "Oosterbeek", "value" => "Oosterbeek"),
    array("label" => "Opheusden", "value" => "Opheusden"),
    array("label" => "OsnabrÃ¼ck Hbf", "value" => "OsnabrÃ¼ck Hbf"),
    array("label" => "Oss", "value" => "Oss"),
    array("label" => "Oss West", "value" => "Oss West"),
    array("label" => "Oudenbosch", "value" => "Oudenbosch"),
    array("label" => "Overveen", "value" => "Overveen"),
    array("label" => "Paris-Nord", "value" => "Paris-Nord"),
    array("label" => "Plochingen", "value" => "Plochingen"),
    array("label" => "Poznan Gl.", "value" => "Poznan Gl."),
    array("label" => "Praha hl.n.", "value" => "Praha hl.n."),
    array("label" => "Praha-Holesovice", "value" => "Praha-Holesovice"),
    array("label" => "Preussen", "value" => "Preussen"),
    array("label" => "Purmerend", "value" => "Purmerend"),
    array("label" => "Purmerend Overwhere", "value" => "Purmerend Overwhere"),
    array("label" => "Purmerend Weidevenne", "value" => "Purmerend Weidevenne"),
    array("label" => "Putten", "value" => "Putten"),
    array("label" => "Puurs", "value" => "Puurs"),
    array("label" => "Raalte", "value" => "Raalte"),
    array("label" => "Rathenow", "value" => "Rathenow"),
    array("label" => "Ravenstein", "value" => "Ravenstein"),
    array("label" => "Reuver", "value" => "Reuver"),
    array("label" => "Rheden", "value" => "Rheden"),
    array("label" => "Rheine", "value" => "Rheine"),
    array("label" => "Rhenen", "value" => "Rhenen"),
    array("label" => "Rijssen", "value" => "Rijssen"),
    array("label" => "Rijswijk", "value" => "Rijswijk"),
    array("label" => "Rilland-Bath", "value" => "Rilland-Bath"),
    array("label" => "Roermond", "value" => "Roermond"),
    array("label" => "Roodeschool", "value" => "Roodeschool"),
    array("label" => "Roosendaal", "value" => "Roosendaal"),
    array("label" => "Rosendahl-Holtwick", "value" => "Rosendahl-Holtwick"),
    array("label" => "Rosmalen", "value" => "Rosmalen"),
    array("label" => "Rotterdam Alexander", "value" => "Rotterdam Alexander"),
    array("label" => "Rotterdam Blaak", "value" => "Rotterdam Blaak"),
    array("label" => "Rotterdam Centraal", "value" => "Rotterdam Centraal"),
    array("label" => "Rotterdam Lombardijen", "value" => "Rotterdam Lombardijen"),
    array("label" => "Rotterdam Noord", "value" => "Rotterdam Noord"),
    array("label" => "Rotterdam Stadion", "value" => "Rotterdam Stadion"),
    array("label" => "Rotterdam Zuid", "value" => "Rotterdam Zuid"),
    array("label" => "Ruisbroek-Sauvegarde", "value" => "Ruisbroek-Sauvegarde"),
    array("label" => "Ruurlo", "value" => "Ruurlo"),
    array("label" => "Rzepin", "value" => "Rzepin"),
    array("label" => "Saalfelden", "value" => "Saalfelden"),
    array("label" => "Santpoort Noord", "value" => "Santpoort Noord"),
    array("label" => "Santpoort Zuid", "value" => "Santpoort Zuid"),
    array("label" => "Sappemeer Oost", "value" => "Sappemeer Oost"),
    array("label" => "Sassenheim", "value" => "Sassenheim"),
    array("label" => "Sauwerd", "value" => "Sauwerd"),
    array("label" => "Schagen", "value" => "Schagen"),
    array("label" => "Scheemda", "value" => "Scheemda"),
    array("label" => "Schelle", "value" => "Schelle"),
    array("label" => "Schiedam Centrum", "value" => "Schiedam Centrum"),
    array("label" => "Schiedam Nieuwland", "value" => "Schiedam Nieuwland"),
    array("label" => "Schin op Geul", "value" => "Schin op Geul"),
    array("label" => "Schinnen", "value" => "Schinnen"),
    array("label" => "Schiphol Airport", "value" => "Schiphol Airport"),
    array("label" => "Schwarzach-St. Veit", "value" => "Schwarzach-St. Veit"),
    array("label" => "Schwelm", "value" => "Schwelm"),
    array("label" => "Schwerte (Ruhr)", "value" => "Schwerte (Ruhr)"),
    array("label" => "Selm", "value" => "Selm"),
    array("label" => "Selm-Beifang", "value" => "Selm-Beifang"),
    array("label" => "Siegburg/Bonn", "value" => "Siegburg/Bonn"),
    array("label" => "Simpelveld", "value" => "Simpelveld"),
    array("label" => "Sinaai", "value" => "Sinaai"),
    array("label" => "Sint-Katelijne-Waver", "value" => "Sint-Katelijne-Waver"),
    array("label" => "Sint-Niklaas", "value" => "Sint-Niklaas"),
    array("label" => "Sittard", "value" => "Sittard"),
    array("label" => "Sliedrecht", "value" => "Sliedrecht"),
    array("label" => "Sliedrecht Baanhoek", "value" => "Sliedrecht Baanhoek"),
    array("label" => "Sneek", "value" => "Sneek"),
    array("label" => "Sneek Noord", "value" => "Sneek Noord"),
    array("label" => "Soest", "value" => "Soest"),
    array("label" => "Soest Zuid", "value" => "Soest Zuid"),
    array("label" => "Soestdijk", "value" => "Soestdijk"),
    array("label" => "Spaubeek", "value" => "Spaubeek"),
    array("label" => "Spekholzerheide", "value" => "Spekholzerheide"),
    array("label" => "St-Mariaburg", "value" => "St-Mariaburg"),
    array("label" => "St. Johann im Pongau", "value" => "St. Johann im Pongau"),
    array("label" => "St. Johann in Tirol", "value" => "St. Johann in Tirol"),
    array("label" => "Stavoren", "value" => "Stavoren"),
    array("label" => "Stedum", "value" => "Stedum"),
    array("label" => "Steenwijk", "value" => "Steenwijk"),
    array("label" => "Steinfurt-Borghorst", "value" => "Steinfurt-Borghorst"),
    array("label" => "Steinfurt-Burgsteinfurt", "value" => "Steinfurt-Burgsteinfurt"),
    array("label" => "Steinfurt-Grottenkamp", "value" => "Steinfurt-Grottenkamp"),
    array("label" => "Stendal", "value" => "Stendal"),
    array("label" => "Stuttgart Hbf", "value" => "Stuttgart Hbf"),
    array("label" => "Susteren", "value" => "Susteren"),
    array("label" => "Swalmen", "value" => "Swalmen"),
    array("label" => "Tantow", "value" => "Tantow"),
    array("label" => "Tegelen", "value" => "Tegelen"),
    array("label" => "Terborg", "value" => "Terborg"),
    array("label" => "Tiel", "value" => "Tiel"),
    array("label" => "Tiel Passewaaij", "value" => "Tiel Passewaaij"),
    array("label" => "Tilburg", "value" => "Tilburg"),
    array("label" => "Tilburg Reeshof", "value" => "Tilburg Reeshof"),
    array("label" => "Tilburg Universiteit", "value" => "Tilburg Universiteit"),
    array("label" => "Tongeren", "value" => "Tongeren"),
    array("label" => "Twello", "value" => "Twello"),
    array("label" => "Uitgeest", "value" => "Uitgeest"),
    array("label" => "Uithuizen", "value" => "Uithuizen"),
    array("label" => "Uithuizermeeden", "value" => "Uithuizermeeden"),
    array("label" => "Ulm Hbf", "value" => "Ulm Hbf"),
    array("label" => "Unna", "value" => "Unna"),
    array("label" => "Usquert", "value" => "Usquert"),
    array("label" => "Usti nad Labem", "value" => "Usti nad Labem"),
    array("label" => "Utrecht Centraal", "value" => "Utrecht Centraal"),
    array("label" => "Utrecht Leidsche Rijn", "value" => "Utrecht Leidsche Rijn"),
    array("label" => "Utrecht Lunetten", "value" => "Utrecht Lunetten"),
    array("label" => "Utrecht Maliebaan", "value" => "Utrecht Maliebaan"),
    array("label" => "Utrecht Overvecht", "value" => "Utrecht Overvecht"),
    array("label" => "Utrecht Terwijde", "value" => "Utrecht Terwijde"),
    array("label" => "Utrecht Zuilen", "value" => "Utrecht Zuilen"),
    array("label" => "Valence TGV", "value" => "Valence TGV"),
    array("label" => "Valkenburg", "value" => "Valkenburg"),
    array("label" => "Varsseveld", "value" => "Varsseveld"),
    array("label" => "Veendam", "value" => "Veendam"),
    array("label" => "Veenendaal Centrum", "value" => "Veenendaal Centrum"),
    array("label" => "Veenendaal West", "value" => "Veenendaal West"),
    array("label" => "Veenendaal-De Klomp", "value" => "Veenendaal-De Klomp"),
    array("label" => "Velp", "value" => "Velp"),
    array("label" => "Venlo", "value" => "Venlo"),
    array("label" => "Venray", "value" => "Venray"),
    array("label" => "Vierlingsbeek", "value" => "Vierlingsbeek"),
    array("label" => "Viersen", "value" => "Viersen"),
    array("label" => "VisÃ©", "value" => "VisÃ©"),
    array("label" => "Vlaardingen Centrum", "value" => "Vlaardingen Centrum"),
    array("label" => "Vlaardingen Oost", "value" => "Vlaardingen Oost"),
    array("label" => "Vlaardingen West", "value" => "Vlaardingen West"),
    array("label" => "Vleuten", "value" => "Vleuten"),
    array("label" => "Vlissingen", "value" => "Vlissingen"),
    array("label" => "Vlissingen Souburg", "value" => "Vlissingen Souburg"),
    array("label" => "Voerendaal", "value" => "Voerendaal"),
    array("label" => "Voorburg", "value" => "Voorburg"),
    array("label" => "Voorhout", "value" => "Voorhout"),
    array("label" => "Voorschoten", "value" => "Voorschoten"),
    array("label" => "Voorst-Empe", "value" => "Voorst-Empe"),
    array("label" => "Vorden", "value" => "Vorden"),
    array("label" => "Vriezenveen", "value" => "Vriezenveen"),
    array("label" => "Vroomshoop", "value" => "Vroomshoop"),
    array("label" => "Vught", "value" => "Vught"),
    array("label" => "Waddinxveen", "value" => "Waddinxveen"),
    array("label" => "Waddinxveen Noord", "value" => "Waddinxveen Noord"),
    array("label" => "Warffum", "value" => "Warffum"),
    array("label" => "Warszawa Centralna", "value" => "Warszawa Centralna"),
    array("label" => "Warszawa Wschodnia", "value" => "Warszawa Wschodnia"),
    array("label" => "Weener", "value" => "Weener"),
    array("label" => "Weert", "value" => "Weert"),
    array("label" => "Weesp", "value" => "Weesp"),
    array("label" => "Wehl", "value" => "Wehl"),
    array("label" => "Westervoort", "value" => "Westervoort"),
    array("label" => "Wezep", "value" => "Wezep"),
    array("label" => "Wien Westbahnhof", "value" => "Wien Westbahnhof"),
    array("label" => "Wierden", "value" => "Wierden"),
    array("label" => "Wijchen", "value" => "Wijchen"),
    array("label" => "Wijhe", "value" => "Wijhe"),
    array("label" => "Wildert", "value" => "Wildert"),
    array("label" => "Winschoten", "value" => "Winschoten"),
    array("label" => "Winsum", "value" => "Winsum"),
    array("label" => "Winterswijk", "value" => "Winterswijk"),
    array("label" => "Winterswijk West", "value" => "Winterswijk West"),
    array("label" => "Woerden", "value" => "Woerden"),
    array("label" => "Wolfheze", "value" => "Wolfheze"),
    array("label" => "Wolfsburg", "value" => "Wolfsburg"),
    array("label" => "Wolvega", "value" => "Wolvega"),
    array("label" => "Workum", "value" => "Workum"),
    array("label" => "Wormerveer", "value" => "Wormerveer"),
    array("label" => "Wuppertal Barmen", "value" => "Wuppertal Barmen"),
    array("label" => "Wuppertal Hbf", "value" => "Wuppertal Hbf"),
    array("label" => "Wuppertal Oberbarmen", "value" => "Wuppertal Oberbarmen"),
    array("label" => "Wuppertal-Vohwinkel", "value" => "Wuppertal-Vohwinkel"),
    array("label" => "WÃ¶rgl", "value" => "WÃ¶rgl"),
    array("label" => "WÃ¼rzburg Hbf", "value" => "WÃ¼rzburg Hbf"),
    array("label" => "Zaandam", "value" => "Zaandam"),
    array("label" => "Zaandam Kogerveld", "value" => "Zaandam Kogerveld"),
    array("label" => "Zaltbommel", "value" => "Zaltbommel"),
    array("label" => "Zandvoort aan Zee", "value" => "Zandvoort aan Zee"),
    array("label" => "Zell am See", "value" => "Zell am See"),
    array("label" => "Zetten-Andelst", "value" => "Zetten-Andelst"),
    array("label" => "Zevenaar", "value" => "Zevenaar"),
    array("label" => "Zevenbergen", "value" => "Zevenbergen"),
    array("label" => "Zoetermeer", "value" => "Zoetermeer"),
    array("label" => "Zoetermeer Oost", "value" => "Zoetermeer Oost"),
    array("label" => "Zuidbroek", "value" => "Zuidbroek"),
    array("label" => "Zuidhorn", "value" => "Zuidhorn"),
    array("label" => "Zutphen", "value" => "Zutphen"),
    array("label" => "Zwijndrecht", "value" => "Zwijndrecht"),
    array("label" => "Zwijndrecht (Belgie)", "value" => "Zwijndrecht (Belgie)"),
    array("label" => "Zwolle", "value" => "Zwolle"),
    array("label" => "ZÃ¼rich HB", "value" => "ZÃ¼rich HB"),
    array("label" => "Ã–tztal", "value" => "Ã–tztal"),
);

$resultaat = array();
foreach ($stations as $station) {
    $stationLabel = $station["label"];
    if (strpos(strtoupper($stationLabel), strtoupper($term)) !== false) {
        array_push($resultaat, $station);
    }
}

echo json_encode($resultaat);
?>